# Generated by Django 5.1.7 on 2025-04-14 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_favorite'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Favorite',
        ),
    ]
