# Generated by Django 5.1.7 on 2025-04-14 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(blank=True, choices=[('', 'Prefer not to say'), ('M', 'Male'), ('F', 'Female'), ('O', 'Other')], default='', max_length=1),
        ),
    ]
