# Generated by Django 5.1.7 on 2025-04-14 10:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_userprofile_gender_alter_userprofile_birth_date'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_id', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('supertype', models.CharField(max_length=50)),
                ('subtypes', models.JSONField(default=list)),
                ('hp', models.CharField(blank=True, max_length=10, null=True)),
                ('types', models.JSONField(default=list)),
                ('number', models.CharField(max_length=20)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('rarity', models.CharField(blank=True, max_length=50, null=True)),
                ('set_name', models.CharField(max_length=100)),
                ('set_series', models.CharField(max_length=100)),
                ('small_image', models.URLField(max_length=500)),
                ('large_image', models.URLField(max_length=500)),
                ('tcgplayer_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cardmarket_url', models.URLField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['name'], name='accounts_po_name_58ca72_idx'), models.Index(fields=['set_name'], name='accounts_po_set_nam_3dbe75_idx'), models.Index(fields=['rarity'], name='accounts_po_rarity_2e3dd6_idx')],
            },
        ),
        migrations.CreateModel(
            name='CardListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.CharField(choices=[('MT', 'Mint'), ('NM', 'Near Mint'), ('EX', 'Excellent'), ('GD', 'Good'), ('LP', 'Lightly Played'), ('PL', 'Played'), ('PR', 'Poor')], max_length=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True)),
                ('is_foil', models.BooleanField(default=False)),
                ('willing_to_trade', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('available', 'Available'), ('pending', 'Trade Pending'), ('completed', 'Trade Completed'), ('cancelled', 'Cancelled')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.pokemoncard')),
                ('cards_wanted', models.ManyToManyField(blank=True, related_name='wanted_in_listings', to='accounts.pokemoncard')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='accounts_ca_status_f66767_idx'), models.Index(fields=['condition'], name='accounts_ca_conditi_6ca69c_idx'), models.Index(fields=['-created_at'], name='accounts_ca_created_178561_idx')],
            },
        ),
    ]
